{% set name = "arq" %}
{% set version = "0.26.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/arq-{{ version }}.tar.gz
  sha256: 362063ea3c726562fb69c723d5b8ee80827fdefda782a8547da5be3d380ac4b1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - arq = arq.cli:cli

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling
  run:
    - python >=3.8
    - redis-py >=4.2.0,<6

    # (extras_require for reddis[hiredis])
    - hiredis >=1.0.0

    - click >=8.0

test:
  imports:
    - arq
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/samuelcolvin/arq
  summary: Job queues in python with asyncio and redis
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
